insert into Localidad values (1,30,'Adolfo Gonzales Chaves');
insert into Localidad values (1,30,'Balcarce');
insert into Localidad values (1,30,'Baradero');
insert into Localidad values (1,30,'Benito Juarez');
insert into Localidad values (1,30,'Alberti');
insert into Localidad values (1,30,'Arrecifes');
insert into Localidad values (1,30,'Almirante Brown');
insert into Localidad values (1,30,'Avellaneda');
insert into Localidad values (1,30,'Ayacucho');
insert into Localidad values (1,30,'Azul');
insert into Localidad values (1,30,'Bahiaa Blanca');
insert into Localidad values (1,30,'Berazategui');
insert into Localidad values (1,30,'Berisso');
insert into Localidad values (1,30,'Boli≠var');
insert into Localidad values (1,30,'Bragado');
insert into Localidad values (1,30,'Adolfo Alsina');
insert into Localidad values (1,30,'Brandsen');
insert into Localidad values (1,30,'Campana');
insert into Localidad values (1,30,'CaÒuelas');
insert into Localidad values (1,30,'Capitan Sarmiento');
insert into Localidad values (1,30,'Carlos Casares');
insert into Localidad values (1,30,'Carlos Tejedor');
insert into Localidad values (1,30,'Carmen de Areco');
insert into Localidad values (1,30,'Castelli');
insert into Localidad values (1,30,'Colon');
insert into Localidad values (1,30,'Coronel de Marina Leonardo Rosales');
insert into Localidad values (1,30,'Coronel Dorrego');
insert into Localidad values (1,30,'Coronel Pringles');
insert into Localidad values (1,30,'Coronel Suarez');
insert into Localidad values (1,30,'Chacabuco');
insert into Localidad values (1,30,'Chascomus');
insert into Localidad values (1,30,'Lezama');
insert into Localidad values (1,30,'Chivilcoy');
insert into Localidad values (1,30,'Daireaux');
insert into Localidad values (1,30,'Dolores');
insert into Localidad values (1,30,'Ensenada');
insert into Localidad values (1,30,'Escobar');
insert into Localidad values (1,30,'Esteban Echeverri≠a');
insert into Localidad values (1,30,'Exaltacion de la Cruz');
insert into Localidad values (1,30,'Ezeiza');
insert into Localidad values (1,30,'Florencio Varela');
insert into Localidad values (1,30,'Florentino Ameghino');
insert into Localidad values (1,30,'General Alvarado');
insert into Localidad values (1,30,'General Alvear');
insert into Localidad values (1,30,'General Arenales');
insert into Localidad values (1,30,'General Belgrano');
insert into Localidad values (1,30,'General Guido');
insert into Localidad values (1,30,'General Juan Madariaga');
insert into Localidad values (1,30,'General la Madrid');
insert into Localidad values (1,30,'General las Heras');
insert into Localidad values (1,30,'General Lavalle');
insert into Localidad values (1,30,'General Paz');
insert into Localidad values (1,30,'General Pinto');
insert into Localidad values (1,30,'General Pueyrredon');
insert into Localidad values (1,30,'General Rodriguez');
insert into Localidad values (1,30,'General San Martin');
insert into Localidad values (1,30,'General Viamonte');
insert into Localidad values (1,30,'General Villegas');
insert into Localidad values (1,30,'Guamini');
insert into Localidad values (1,30,'Hipolito Yrigoyen');
insert into Localidad values (1,30,'Hurlingham');
insert into Localidad values (1,30,'Ituzaingo');
insert into Localidad values (1,30,'Jose C. Paz');
insert into Localidad values (1,30,'Junin');
insert into Localidad values (1,30,'La Costa');
insert into Localidad values (1,30,'La Matanza');
insert into Localidad values (1,30,'Lan√∫s');
insert into Localidad values (1,30,'La Plata');
insert into Localidad values (1,30,'Laprida');
insert into Localidad values (1,30,'Las Flores');
insert into Localidad values (1,30,'Leandro N. Alem');
insert into Localidad values (1,30,'Lincoln');
insert into Localidad values (1,30,'Lober≠a');
insert into Localidad values (1,30,'Lobos');
insert into Localidad values (1,30,'Lomas de Zamora');
insert into Localidad values (1,30,'Lujan');
insert into Localidad values (1,30,'Magdalena');
insert into Localidad values (1,30,'Maipu');
insert into Localidad values (1,30,'Malvinas Argentinas');
insert into Localidad values (1,30,'Mar Chiquita');
insert into Localidad values (1,30,'Marcos Paz');
insert into Localidad values (1,30,'Mercedes');
insert into Localidad values (1,30,'Merlo');
insert into Localidad values (1,30,'Monte');
insert into Localidad values (1,30,'Monte Hermoso');
insert into Localidad values (1,30,'Moreno');
insert into Localidad values (1,30,'Mor0n');
insert into Localidad values (1,30,'Navarro');
insert into Localidad values (1,30,'Necochea');
insert into Localidad values (1,30,'9 de Julio');
insert into Localidad values (1,30,'Olavarria');
insert into Localidad values (1,30,'Patagones');
insert into Localidad values (1,30,'Pehuajo');
insert into Localidad values (1,30,'Pellegrini');
insert into Localidad values (1,30,'Pergamino');
insert into Localidad values (1,30,'Pila');
insert into Localidad values (1,30,'Pilar');
insert into Localidad values (1,30,'Pinamar');
insert into Localidad values (1,30,'Presidente Peron');
insert into Localidad values (1,30,'Puan');
insert into Localidad values (1,30,'Punta Indio');
insert into Localidad values (1,30,'Quilmes');
insert into Localidad values (1,30,'Ramallo');
insert into Localidad values (1,30,'Rauch');
insert into Localidad values (1,30,'Rivadavia');
insert into Localidad values (1,30,'Rojas');
insert into Localidad values (1,30,'Roque Perez');
insert into Localidad values (1,30,'Saavedra');
insert into Localidad values (1,30,'Saladillo');
insert into Localidad values (1,30,'Salto');
insert into Localidad values (1,30,'Salliquela');
insert into Localidad values (1,30,'San Andres de Giles');
insert into Localidad values (1,30,'San Antonio de Areco');
insert into Localidad values (1,30,'San Cayetano');
insert into Localidad values (1,30,'San Fernando');
insert into Localidad values (1,30,'San Isidro');
insert into Localidad values (1,30,'San Miguel');
insert into Localidad values (1,30,'San Nicol√°s');
insert into Localidad values (1,30,'San Pedro');
insert into Localidad values (1,30,'San Vicente');
insert into Localidad values (1,30,'Suipacha');
insert into Localidad values (1,30,'Tandil');
insert into Localidad values (1,30,'Tapalque');
insert into Localidad values (1,30,'Tigre');
insert into Localidad values (1,30,'Tordillo');
insert into Localidad values (1,30,'Tornquist');
insert into Localidad values (1,30,'Trenque Lauquen');
insert into Localidad values (1,30,'Tres Arroyos');
insert into Localidad values (1,30,'Tres de Febrero');
insert into Localidad values (1,30,'Tres Lomas');
insert into Localidad values (1,30,'25 de Mayo');
insert into Localidad values (1,30,'Vicente Lopez');
insert into Localidad values (1,30,'Villa Gesell');
insert into Localidad values (1,30,'Villarino');
insert into Localidad values (1,30,'Zarate');
